language: cpp

compiler:
    - clang
    - gcc

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2

script:
  - mkdir build
  - cd build
  - cmake -DRUN_TESTS=ON ..
  - cmake --build .
  - ctest --output-on-failure
