language: cpp
before_install:
  - sudo apt-get install -y libbenchmark-dev

compiler: clang
dist: xenial

script:
  - cd build
  - cmake -DRUN_TESTS=ON ..
  - cmake --build .
  - ctest --output-on-failure
