language: cpp

compiler:
    - clang
    - gcc
os:
    - linux
    - osx

dist: bionic
osx_image: xcode10.2

script:
  - mkdir build
  - cd build
  - cmake -DRUN_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON ..
  - cmake --build .
  - ctest --output-on-failure
